blank_issues_enabled: true
contact_links:
  - name: "\U0001F1E8\U0001F1F3 Gitee Issues"
    url: https://gitee.com/shiqkuangsan/Recopy/issues
    about: For users in China, you can also report issues on Gitee.
